/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface GrantClawRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "milestoneSeen"
      | "proposals"
      | "submitMilestone"
      | "submitProposal"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "MilestoneSubmitted" | "ProposalSubmitted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "milestoneSeen",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "proposals",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitMilestone",
    values: [BytesLike, BytesLike, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "submitProposal",
    values: [BytesLike, string, string, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "milestoneSeen",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "proposals", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "submitMilestone",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitProposal",
    data: BytesLike
  ): Result;
}

export namespace MilestoneSubmittedEvent {
  export type InputTuple = [
    proposalHash: BytesLike,
    milestoneHash: BytesLike,
    submitter: AddressLike,
    title: string,
    uri: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    proposalHash: string,
    milestoneHash: string,
    submitter: string,
    title: string,
    uri: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    proposalHash: string;
    milestoneHash: string;
    submitter: string;
    title: string;
    uri: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProposalSubmittedEvent {
  export type InputTuple = [
    proposalHash: BytesLike,
    submitter: AddressLike,
    grantId: string,
    title: string,
    uri: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    proposalHash: string,
    submitter: string,
    grantId: string,
    title: string,
    uri: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    proposalHash: string;
    submitter: string;
    grantId: string;
    title: string;
    uri: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface GrantClawRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): GrantClawRegistry;
  waitForDeployment(): Promise<this>;

  interface: GrantClawRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  milestoneSeen: TypedContractMethod<
    [arg0: BytesLike, arg1: BytesLike],
    [boolean],
    "view"
  >;

  proposals: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, string, string, bigint] & {
        proposalHash: string;
        submitter: string;
        grantId: string;
        title: string;
        uri: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  submitMilestone: TypedContractMethod<
    [
      proposalHash: BytesLike,
      milestoneHash: BytesLike,
      title: string,
      uri: string
    ],
    [void],
    "nonpayable"
  >;

  submitProposal: TypedContractMethod<
    [proposalHash: BytesLike, grantId: string, title: string, uri: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "milestoneSeen"
  ): TypedContractMethod<[arg0: BytesLike, arg1: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "proposals"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, string, string, bigint] & {
        proposalHash: string;
        submitter: string;
        grantId: string;
        title: string;
        uri: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "submitMilestone"
  ): TypedContractMethod<
    [
      proposalHash: BytesLike,
      milestoneHash: BytesLike,
      title: string,
      uri: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitProposal"
  ): TypedContractMethod<
    [proposalHash: BytesLike, grantId: string, title: string, uri: string],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "MilestoneSubmitted"
  ): TypedContractEvent<
    MilestoneSubmittedEvent.InputTuple,
    MilestoneSubmittedEvent.OutputTuple,
    MilestoneSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "ProposalSubmitted"
  ): TypedContractEvent<
    ProposalSubmittedEvent.InputTuple,
    ProposalSubmittedEvent.OutputTuple,
    ProposalSubmittedEvent.OutputObject
  >;

  filters: {
    "MilestoneSubmitted(bytes32,bytes32,address,string,string,uint256)": TypedContractEvent<
      MilestoneSubmittedEvent.InputTuple,
      MilestoneSubmittedEvent.OutputTuple,
      MilestoneSubmittedEvent.OutputObject
    >;
    MilestoneSubmitted: TypedContractEvent<
      MilestoneSubmittedEvent.InputTuple,
      MilestoneSubmittedEvent.OutputTuple,
      MilestoneSubmittedEvent.OutputObject
    >;

    "ProposalSubmitted(bytes32,address,string,string,string,uint256)": TypedContractEvent<
      ProposalSubmittedEvent.InputTuple,
      ProposalSubmittedEvent.OutputTuple,
      ProposalSubmittedEvent.OutputObject
    >;
    ProposalSubmitted: TypedContractEvent<
      ProposalSubmittedEvent.InputTuple,
      ProposalSubmittedEvent.OutputTuple,
      ProposalSubmittedEvent.OutputObject
    >;
  };
}
