/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { GrantClawRegistry } from "./GrantClawRegistry";
export * as factories from "./factories";
export { GrantClawRegistry__factory } from "./factories/GrantClawRegistry__factory";
